// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package extras_ee2d5c

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}

func init() {
}

// split_fieldcontext_.gotpl — fieldContext for Mutation.pingFromExtras
func __splitFieldContext_Mutation_pingFromExtras(_ context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Mutation",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

// split_fieldcontext_.gotpl — fieldContext for Query.goodbyeFromExtras
func __splitFieldContext_Query_goodbyeFromExtras(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	rawArgs := field.ArgumentMap(ec.GetOperationContext().Variables)
	argsHandler, ok := shardruntime.LookupArgs(splitScope, "field_Query_goodbyeFromExtras_args")
	if !ok {
		return nil, fmt.Errorf("no args handler for %q", "field_Query_goodbyeFromExtras_args")
	}
	if fc.Args, err = argsHandler(ctx, ec, rawArgs); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

// split_args_.gotpl — args for Query.goodbyeFromExtras
func __splitArgs_field_Query_goodbyeFromExtras_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}
