// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package extras_ee2d5c

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}

func init() {
}

func __resolveField_Mutation(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return ec.InvokeResolver(ctx, "Mutation", "pingFromExtras", obj)
	default:
		return nil, fmt.Errorf("unknown field index %d for Mutation", fieldIdx)
	}
}

func __resolveField_Query(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return ec.InvokeResolver(ctx, "Query", "goodbyeFromExtras", obj)
	default:
		return nil, fmt.Errorf("unknown field index %d for Query", fieldIdx)
	}
}

// split_args_.gotpl — args for Query.goodbyeFromExtras
func __splitArgs_field_Query_goodbyeFromExtras_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}
