// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package extras_ee2d5c

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
)

func init() {
	shardruntime.RegisterField(splitScope, "Mutation", "pingFromExtras", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField, obj any) graphql.Marshaler {
		return __splitField_Mutation_pingFromExtras(ctx, ec, field, obj)
	})
	shardruntime.RegisterField(splitScope, "Query", "goodbyeFromExtras", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField, obj any) graphql.Marshaler {
		return __splitField_Query_goodbyeFromExtras(ctx, ec, field, obj)
	})
	shardruntime.RegisterFieldContext(splitScope, "Mutation", "pingFromExtras", __splitFieldContext_Mutation_pingFromExtras)
	shardruntime.RegisterFieldContext(splitScope, "Query", "goodbyeFromExtras", __splitFieldContext_Query_goodbyeFromExtras)
	shardruntime.RegisterArgs(splitScope, "field_Query_goodbyeFromExtras_args", __splitArgs_field_Query_goodbyeFromExtras_args)
}
