// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package extras_ee2d5c

import (
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
)

func shardDescFieldsChunk0() []shardruntime.ShardFieldDef {
	return []shardruntime.ShardFieldDef{
		{Object: "Mutation", Name: "pingFromExtras", Def: shardruntime.FieldDef{
			Resolve:      __resolveField_Mutation,
			FieldIdx:     0,
			MarshalCodec: "marshalNString2string",
			NonNull:      true,
			PanicHandled: true,
			IsMethod:     true,
			IsResolver:   true,
			ReturnType:   type_String,
		}},
		{Object: "Query", Name: "goodbyeFromExtras", Def: shardruntime.FieldDef{
			Resolve:      __resolveField_Query,
			FieldIdx:     0,
			MarshalCodec: "marshalNString2string",
			NonNull:      true,
			PanicHandled: true,
			IsMethod:     true,
			IsResolver:   true,
			ArgsKey:      "field_Query_goodbyeFromExtras_args",
			ReturnType:   type_String,
		}},
	}
}

func shardDescFields() []shardruntime.ShardFieldDef {
	out := make([]shardruntime.ShardFieldDef, 0)
	out = append(out, shardDescFieldsChunk0()...)
	return out
}

var ShardDesc = shardruntime.ShardDescriptor{
	Scope:  splitScope,
	Fields: shardDescFields(),
}

func init() {
	shardruntime.RegisterArgs(splitScope, "field_Query_goodbyeFromExtras_args", __splitArgs_field_Query_goodbyeFromExtras_args)
}
