// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package extras_ee2d5c

import (
	"context"

	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
)

func init() {
	shardruntime.RegisterFieldDef(splitScope, "Mutation", "pingFromExtras", shardruntime.FieldDef{
		Resolve: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (any, error) {
			return ec.InvokeResolver(ctx, "Mutation", "pingFromExtras", obj)
		},
		MarshalCodec: "marshalNString2string",
		NonNull:      true,
		PanicHandled: true,
		IsMethod:     true,
		IsResolver:   true,
		ReturnType:   type_String,
	})
	shardruntime.RegisterFieldDef(splitScope, "Query", "goodbyeFromExtras", shardruntime.FieldDef{
		Resolve: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (any, error) {
			return ec.InvokeResolver(ctx, "Query", "goodbyeFromExtras", obj)
		},
		MarshalCodec: "marshalNString2string",
		NonNull:      true,
		PanicHandled: true,
		IsMethod:     true,
		IsResolver:   true,
		ArgsKey:      "field_Query_goodbyeFromExtras_args",
		ReturnType:   type_String,
	})
	shardruntime.RegisterArgs(splitScope, "field_Query_goodbyeFromExtras_args", __splitArgs_field_Query_goodbyeFromExtras_args)
}
