// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package object_generic

import (
	"context"

	"github.com/99designs/gqlgen/codegen/testdata/object_generic/graph"
	"github.com/99designs/gqlgen/codegen/testdata/object_generic/graph/model"
)

type Stub struct {
	QueryResolver struct {
		User func(ctx context.Context, id string) (*model.User, error)
	}
}

func (r *Stub) Query() graph.QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) User(ctx context.Context, id string) (*model.User, error) {
	return r.QueryResolver.User(ctx, id)
}
