// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

func init() {
	shardruntime.RegisterObject(splitScope, "Query", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return _Query(ctx, ec, sel)
	})
}

var queryImplementors = []string{"Query"}

func _Query(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, queryImplementors)
	ctx = graphql.WithFieldContext(ctx, &graphql.FieldContext{
		Object: "Query",
	})

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		innerCtx := graphql.WithRootFieldContext(ctx, &graphql.RootFieldContext{
			Object: field.Name,
			Field:  field,
		})

		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("Query")
		case "hello":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec.ResolveField(ctx, "Query", "hello", field, nil)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.GetOperationContext().RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "__type":
			out.Values[i] = ec.GetOperationContext().RootResolverMiddleware(innerCtx, func(ctx context.Context) (res graphql.Marshaler) {
				return ec.ResolveField(ctx, "Query", "__type", field, nil)
			})
		case "__schema":
			out.Values[i] = ec.GetOperationContext().RootResolverMiddleware(innerCtx, func(ctx context.Context) (res graphql.Marshaler) {
				return ec.ResolveField(ctx, "Query", "__schema", field, nil)
			})
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// split_fields_.gotpl — field
func __splitField_Query___schema(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField, obj any) graphql.Marshaler {
	return graphql.ResolveField[any](ctx, ec.GetOperationContext(), field,
		// fieldContext provider
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			handler, ok := ec.LookupFieldContextHandler("Query", "__schema")
			if !ok {
				return nil, fmt.Errorf("no field context for Query.__schema")
			}
			return handler(ctx, ec, field)
		},
		// resolver
		func(ctx context.Context) (any, error) {
			return ec.InvokeResolver(ctx, "Query", "__schema", obj)
		},
		// directives
		nil,
		// marshaler
		func(ctx context.Context, sel ast.SelectionSet, v any) graphql.Marshaler {
			return ec.MarshalCodec(ctx, "marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema", sel, v)
		},
		true, false,
	)
}

// split_fields_.gotpl — field
func __splitField_Query___type(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField, obj any) graphql.Marshaler {
	return graphql.ResolveField[any](ctx, ec.GetOperationContext(), field,
		// fieldContext provider
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			handler, ok := ec.LookupFieldContextHandler("Query", "__type")
			if !ok {
				return nil, fmt.Errorf("no field context for Query.__type")
			}
			return handler(ctx, ec, field)
		},
		// resolver
		func(ctx context.Context) (any, error) {
			return ec.InvokeResolver(ctx, "Query", "__type", obj)
		},
		// directives
		nil,
		// marshaler
		func(ctx context.Context, sel ast.SelectionSet, v any) graphql.Marshaler {
			return ec.MarshalCodec(ctx, "marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType", sel, v)
		},
		true, false,
	)
}

// split_fields_.gotpl — field
func __splitField_Query_hello(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField, obj any) graphql.Marshaler {
	return graphql.ResolveField[any](ctx, ec.GetOperationContext(), field,
		// fieldContext provider
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			handler, ok := ec.LookupFieldContextHandler("Query", "hello")
			if !ok {
				return nil, fmt.Errorf("no field context for Query.hello")
			}
			return handler(ctx, ec, field)
		},
		// resolver
		func(ctx context.Context) (any, error) {
			return ec.InvokeResolver(ctx, "Query", "hello", obj)
		},
		// directives
		nil,
		// marshaler
		func(ctx context.Context, sel ast.SelectionSet, v any) graphql.Marshaler {
			return ec.MarshalCodec(ctx, "marshalNString2string", sel, v)
		},
		true, true,
	)
}

// split_fieldcontext_.gotpl — fieldContext for Query.__schema
func __splitFieldContext_Query___schema(_ context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "description":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "description")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.description")
				}
				return handler(ctx, ec, field)
			case "types":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "types")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.types")
				}
				return handler(ctx, ec, field)
			case "queryType":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "queryType")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.queryType")
				}
				return handler(ctx, ec, field)
			case "mutationType":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "mutationType")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.mutationType")
				}
				return handler(ctx, ec, field)
			case "subscriptionType":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "subscriptionType")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.subscriptionType")
				}
				return handler(ctx, ec, field)
			case "directives":
				handler, ok := ec.LookupFieldContextHandler("__Schema", "directives")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Schema.directives")
				}
				return handler(ctx, ec, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type __Schema", field.Name)
		},
	}
	return fc, nil
}

// split_fieldcontext_.gotpl — fieldContext for Query.__type
func __splitFieldContext_Query___type(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "kind":
				handler, ok := ec.LookupFieldContextHandler("__Type", "kind")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.kind")
				}
				return handler(ctx, ec, field)
			case "name":
				handler, ok := ec.LookupFieldContextHandler("__Type", "name")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.name")
				}
				return handler(ctx, ec, field)
			case "description":
				handler, ok := ec.LookupFieldContextHandler("__Type", "description")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.description")
				}
				return handler(ctx, ec, field)
			case "specifiedByURL":
				handler, ok := ec.LookupFieldContextHandler("__Type", "specifiedByURL")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.specifiedByURL")
				}
				return handler(ctx, ec, field)
			case "fields":
				handler, ok := ec.LookupFieldContextHandler("__Type", "fields")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.fields")
				}
				return handler(ctx, ec, field)
			case "interfaces":
				handler, ok := ec.LookupFieldContextHandler("__Type", "interfaces")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.interfaces")
				}
				return handler(ctx, ec, field)
			case "possibleTypes":
				handler, ok := ec.LookupFieldContextHandler("__Type", "possibleTypes")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.possibleTypes")
				}
				return handler(ctx, ec, field)
			case "enumValues":
				handler, ok := ec.LookupFieldContextHandler("__Type", "enumValues")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.enumValues")
				}
				return handler(ctx, ec, field)
			case "inputFields":
				handler, ok := ec.LookupFieldContextHandler("__Type", "inputFields")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.inputFields")
				}
				return handler(ctx, ec, field)
			case "ofType":
				handler, ok := ec.LookupFieldContextHandler("__Type", "ofType")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.ofType")
				}
				return handler(ctx, ec, field)
			case "isOneOf":
				handler, ok := ec.LookupFieldContextHandler("__Type", "isOneOf")
				if !ok {
					return nil, fmt.Errorf("no field context handler for __Type.isOneOf")
				}
				return handler(ctx, ec, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type __Type", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	rawArgs := field.ArgumentMap(ec.GetOperationContext().Variables)
	argsHandler, ok := shardruntime.LookupArgs(splitScope, "field_Query___type_args")
	if !ok {
		return nil, fmt.Errorf("no args handler for %q", "field_Query___type_args")
	}
	if fc.Args, err = argsHandler(ctx, ec, rawArgs); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

// split_fieldcontext_.gotpl — fieldContext for Query.hello
func __splitFieldContext_Query_hello(ctx context.Context, ec shardruntime.ObjectExecutionContext, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	rawArgs := field.ArgumentMap(ec.GetOperationContext().Variables)
	argsHandler, ok := shardruntime.LookupArgs(splitScope, "field_Query_hello_args")
	if !ok {
		return nil, fmt.Errorf("no args handler for %q", "field_Query_hello_args")
	}
	if fc.Args, err = argsHandler(ctx, ec, rawArgs); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

// split_args_.gotpl — args for Query.__type
func __splitArgs_field_Query___type_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}

// split_args_.gotpl — args for Query.hello
func __splitArgs_field_Query_hello_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}

// split_codecs_.gotpl — marshal
func marshalO__Schema2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__Schema")
	if !ok {
		panic("missing object shard handler for __Schema")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	handler, ok := shardruntime.LookupObject(splitScope, "__Schema")
	if !ok {
		panic("missing object shard handler for __Schema")
	}
	return handler(ctx, ec, sel, value)
}
