// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package omittable_input

import (
	"context"
	"fmt"
	"reflect"
	"time"

	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/model"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}

func init() {
}

// split_args_.gotpl — args for Query.inputOmittable
func __splitArgs_field_Query_inputOmittable_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 model.OmittableInput
	if tmp, ok := rawArgs["arg"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("arg"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNOmittableInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐOmittableInput", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(model.OmittableInput)
	}
	args["arg"] = arg0
	return args, nil
}

// split_inputs_.gotpl
func __splitInput_OmittableInput(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (model.OmittableInput, error) {
	// If already unmarshaled to the correct type, return directly.
	if typed, ok := obj.(model.OmittableInput); ok {
		return typed, nil
	}
	if typed, ok := obj.(*model.OmittableInput); ok {
		if typed == nil {
			var zero model.OmittableInput
			return zero, nil
		}
		return *typed, nil
	}
	var it model.OmittableInput
	if obj == nil {
		return it, nil
	}
	asMap := map[string]any{}
	rawMap, ok := obj.(map[string]any)
	if !ok {
		return it, fmt.Errorf("unmarshalInputOmittableInput: expected map[string]any, got %T", obj)
	}
	for k, v := range rawMap {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"id", "bool", "str", "int", "time", "enum", "scalar", "object"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "id":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("id"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOID2ᚖstring", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.ID = graphql.OmittableOf(data.(*string))
			} else {
				it.ID = graphql.OmittableOf[*string](nil)
			}
		case "bool":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("bool"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOBoolean2ᚖbool", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Bool = graphql.OmittableOf(data.(*bool))
			} else {
				it.Bool = graphql.OmittableOf[*bool](nil)
			}
		case "str":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("str"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOString2ᚖstring", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Str = graphql.OmittableOf(data.(*string))
			} else {
				it.Str = graphql.OmittableOf[*string](nil)
			}
		case "int":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("int"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOInt2ᚖint", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Int = graphql.OmittableOf(data.(*int))
			} else {
				it.Int = graphql.OmittableOf[*int](nil)
			}
		case "time":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("time"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOTime2ᚖtimeᚐTime", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Time = graphql.OmittableOf(data.(*time.Time))
			} else {
				it.Time = graphql.OmittableOf[*time.Time](nil)
			}
		case "enum":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("enum"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐStatus", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Enum = graphql.OmittableOf(data.(*model.Status))
			} else {
				it.Enum = graphql.OmittableOf[*model.Status](nil)
			}
		case "scalar":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("scalar"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOThirdParty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐThirdParty", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Scalar = graphql.OmittableOf(data.(*model.ThirdParty))
			} else {
				it.Scalar = graphql.OmittableOf[*model.ThirdParty](nil)
			}
		case "object":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("object"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalOOuterInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐOuterInput", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Object = graphql.OmittableOf(data.(*model.OuterInput))
			} else {
				it.Object = graphql.OmittableOf[*model.OuterInput](nil)
			}
		}
	}

	return it, nil
}

// split_inputs_.gotpl
func __splitInput_OuterInput(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (model.OuterInput, error) {
	// If already unmarshaled to the correct type, return directly.
	if typed, ok := obj.(model.OuterInput); ok {
		return typed, nil
	}
	if typed, ok := obj.(*model.OuterInput); ok {
		if typed == nil {
			var zero model.OuterInput
			return zero, nil
		}
		return *typed, nil
	}
	var it model.OuterInput
	if obj == nil {
		return it, nil
	}
	asMap := map[string]any{}
	rawMap, ok := obj.(map[string]any)
	if !ok {
		return it, fmt.Errorf("unmarshalInputOuterInput: expected map[string]any, got %T", obj)
	}
	for k, v := range rawMap {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"inner"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "inner":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("inner"))
			data, err := ec.UnmarshalCodec(ctx, "unmarshalNInnerInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐInnerInput", v)
			if err != nil {
				return it, err
			}
			if data != nil {
				it.Inner = data.(*model.InnerInput)
			}
		}
	}

	return it, nil
}

// split_codecs_.gotpl — marshal
func marshalOBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	_ = ctx
	v := value.(bool)
	res := graphql.MarshalBoolean(v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOBoolean2ᚖbool(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	_ = sel
	_ = ctx
	v := value.(*bool)
	res := graphql.MarshalBoolean(*v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOID2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	_ = ctx
	v := value.(string)
	res := graphql.MarshalID(v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOID2ᚖstring(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	_ = sel
	_ = ctx
	v := value.(*string)
	res := graphql.MarshalID(*v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOStatus2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐStatus(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	return value.(graphql.Marshaler)
}

// split_codecs_.gotpl — marshal
func marshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐStatus(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	return value.(graphql.Marshaler)
}

// split_codecs_.gotpl — marshal
func marshalOTime2timeᚐTime(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	_ = ctx
	v := value.(time.Time)
	res := graphql.MarshalTime(v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOTime2ᚖtimeᚐTime(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	_ = sel
	_ = ctx
	v := value.(*time.Time)
	res := graphql.MarshalTime(*v)
	return res
}

// split_codecs_.gotpl — unmarshal
func unmarshalNOmittableInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐOmittableInput(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := __splitInput_OmittableInput(ctx, ec, value)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalBoolean(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOBoolean2ᚖbool(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalBoolean(value)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}
	return &res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOID2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalID(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOID2ᚖstring(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalID(value)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}
	return &res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOOuterInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐOuterInput(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := __splitInput_OuterInput(ctx, ec, value)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOOuterInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐOuterInput(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := __splitInput_OuterInput(ctx, ec, value)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOStatus2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐStatus(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	var res model.Status
	err := res.UnmarshalGQL(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐStatus(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	var res = new(model.Status)
	err := res.UnmarshalGQL(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOTime2timeᚐTime(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalTime(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOTime2ᚖtimeᚐTime(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalTime(value)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}
	return &res, nil
}
