// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
)

// region    ************************** generated!.gotpl **************************

type HybridInputResolver interface {
	Resolved(ctx context.Context, obj *HybridInput, data string) error
}
type HybridNestedResolver interface {
	Resolved(ctx context.Context, obj *HybridNested, data string) error
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    ************************** directives.gotpl **************************

// endregion ************************** directives.gotpl **************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

func (ec *executionContext) unmarshalInputHybridInput(ctx context.Context, obj any) (HybridInput, error) {
	var it HybridInput
	if obj == nil {
		return it, nil
	}

	asMap := map[string]any{}
	rawMap, ok := obj.(map[string]any)
	if !ok {
		return it, fmt.Errorf("unmarshalInputHybridInput: expected map[string]any, got %T", obj)
	}
	for k, v := range rawMap {
		asMap[k] = v
	}

	if _, present := asMap["withDefault"]; !present {
		asMap["withDefault"] = "fromDefault"
	}

	plain := make(map[string]any, len(asMap))
	for k, v := range asMap {
		switch k {
		case "directed", "resolved", "nested", "nestedList", "selfRef":
		default:
			plain[k] = v
		}
	}
	if err := it.UnmarshalGQLContext(ctx, plain); err != nil {
		return it, err
	}

	fieldsInOrder := [...]string{"directed", "resolved", "nested", "nestedList", "selfRef"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "directed":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("directed"))
			directive0 := func(ctx context.Context) (any, error) { return ec.unmarshalNString2string(ctx, v) }

			directive1 := func(ctx context.Context) (any, error) {
				if ec.Directives.ToUpper == nil {
					var zeroVal string
					return zeroVal, errors.New("directive toUpper is not implemented")
				}
				return ec.Directives.ToUpper(ctx, obj, directive0)
			}

			tmp, err := directive1(ctx)
			if err != nil {
				return it, graphql.ErrorOnPath(ctx, err)
			}
			if data, ok := tmp.(string); ok {
				it.Directed = data
			} else {
				err := fmt.Errorf(`unexpected type %T from directive, should be string`, tmp)
				return it, graphql.ErrorOnPath(ctx, err)
			}
		case "resolved":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("resolved"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			if err = ec.Resolvers.HybridInput().Resolved(ctx, &it, data); err != nil {
				return it, err
			}
		case "nested":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("nested"))
			data, err := ec.unmarshalOHybridNested2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNested(ctx, v)
			if err != nil {
				return it, err
			}
			it.Nested = data
		case "nestedList":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("nestedList"))
			data, err := ec.unmarshalOHybridNested2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNestedᚄ(ctx, v)
			if err != nil {
				return it, err
			}
			it.NestedList = data
		case "selfRef":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("selfRef"))
			data, err := ec.unmarshalOHybridInput2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInputᚄ(ctx, v)
			if err != nil {
				return it, err
			}
			it.SelfRef = data
		}
	}
	return it, nil
}

func (ec *executionContext) unmarshalInputHybridNested(ctx context.Context, obj any) (HybridNested, error) {
	var it HybridNested
	if obj == nil {
		return it, nil
	}

	asMap := map[string]any{}
	rawMap, ok := obj.(map[string]any)
	if !ok {
		return it, fmt.Errorf("unmarshalInputHybridNested: expected map[string]any, got %T", obj)
	}
	for k, v := range rawMap {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"gated", "resolved", "deeper"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "gated":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("gated"))
			directive0 := func(ctx context.Context) (any, error) { return ec.unmarshalNString2string(ctx, v) }

			directive1 := func(ctx context.Context) (any, error) {
				if ec.Directives.ToUpper == nil {
					var zeroVal string
					return zeroVal, errors.New("directive toUpper is not implemented")
				}
				return ec.Directives.ToUpper(ctx, obj, directive0)
			}

			tmp, err := directive1(ctx)
			if err != nil {
				return it, graphql.ErrorOnPath(ctx, err)
			}
			if data, ok := tmp.(string); ok {
				it.Gated = data
			} else {
				err := fmt.Errorf(`unexpected type %T from directive, should be string`, tmp)
				return it, graphql.ErrorOnPath(ctx, err)
			}
		case "resolved":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("resolved"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			if err = ec.Resolvers.HybridNested().Resolved(ctx, &it, data); err != nil {
				return it, err
			}
		case "deeper":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("deeper"))
			data, err := ec.unmarshalOHybridNested2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNested(ctx, v)
			if err != nil {
				return it, err
			}
			it.Deeper = data
		}
	}
	return it, nil
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) unmarshalNHybridInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInput(ctx context.Context, v any) (HybridInput, error) {
	res, err := ec.unmarshalInputHybridInput(ctx, v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalNHybridInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInput(ctx context.Context, v any) (*HybridInput, error) {
	res, err := ec.unmarshalInputHybridInput(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalNHybridNested2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNested(ctx context.Context, v any) (*HybridNested, error) {
	res, err := ec.unmarshalInputHybridNested(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalOHybridInput2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInputᚄ(ctx context.Context, v any) ([]*HybridInput, error) {
	if v == nil {
		return nil, nil
	}
	var vSlice []any
	vSlice = graphql.CoerceList(v)
	var err error
	res := make([]*HybridInput, len(vSlice))
	for i := range vSlice {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithIndex(i))
		res[i], err = ec.unmarshalNHybridInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInput(ctx, vSlice[i])
		if err != nil {
			return nil, err
		}
	}
	return res, nil
}

func (ec *executionContext) unmarshalOHybridInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridInput(ctx context.Context, v any) (*HybridInput, error) {
	if v == nil {
		return nil, nil
	}
	res, err := ec.unmarshalInputHybridInput(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalOHybridNested2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNestedᚄ(ctx context.Context, v any) ([]*HybridNested, error) {
	if v == nil {
		return nil, nil
	}
	var vSlice []any
	vSlice = graphql.CoerceList(v)
	var err error
	res := make([]*HybridNested, len(vSlice))
	for i := range vSlice {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithIndex(i))
		res[i], err = ec.unmarshalNHybridNested2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNested(ctx, vSlice[i])
		if err != nil {
			return nil, err
		}
	}
	return res, nil
}

func (ec *executionContext) unmarshalOHybridNested2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐHybridNested(ctx context.Context, v any) (*HybridNested, error) {
	if v == nil {
		return nil, nil
	}
	res, err := ec.unmarshalInputHybridNested(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

// endregion ***************************** type.gotpl *****************************
