// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package splitpackages

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Query struct {
		Hello func(childComplexity int, name string) int
	}
}

type QueryResolver interface {
	Hello(ctx context.Context, name string) (string, error)
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "Query.hello":
		if e.complexity.Query.Hello == nil {
			break
		}

		argsHandler, ok := shardruntime.LookupArgs("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "field_Query_hello_args")
		if !ok {
			return 0, false
		}
		args, err := argsHandler(ctx, &ec, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Hello(childComplexity, args["name"].(string)), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		shardruntime.ListInputUnmarshalers("github.com/99designs/gqlgen/codegen/testserver/splitpackages", &ec)...,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) IntrospectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) IntrospectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

func (ec *executionContext) GetOperationContext() *graphql.OperationContext {
	return ec.OperationContext
}

func (ec *executionContext) ProcessDeferredGroup(dg graphql.DeferredGroup) {
	ec.processDeferredGroup(dg)
}

func (ec *executionContext) AddDeferred(delta int32) {
	atomic.AddInt32(&ec.deferred, delta)
}

func (ec *executionContext) ResolveField(ctx context.Context, objectName, fieldName string, field graphql.CollectedField, obj any) graphql.Marshaler {
	handler, ok := shardruntime.LookupField("github.com/99designs/gqlgen/codegen/testserver/splitpackages", objectName, fieldName)
	if !ok {
		panic(fmt.Sprintf("unknown field %s.%s", objectName, fieldName))
	}

	return handler(ctx, ec, field, obj)
}

func (ec *executionContext) ResolveStreamField(ctx context.Context, objectName, fieldName string, field graphql.CollectedField, _ any) func(ctx context.Context) graphql.Marshaler {
	handler, ok := shardruntime.LookupStreamField("github.com/99designs/gqlgen/codegen/testserver/splitpackages", objectName, fieldName)
	if !ok {
		panic(fmt.Sprintf("unknown stream field %s.%s", objectName, fieldName))
	}

	return handler(ctx, ec, field, nil)
}

func (ec *executionContext) MarshalCodec(ctx context.Context, funcName string, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupCodecMarshal("github.com/99designs/gqlgen/codegen/testserver/splitpackages", funcName)
	if !ok {
		panic(fmt.Errorf("unknown codec marshal function %s", funcName))
	}

	return handler(ctx, ec, sel, value)
}

func (ec *executionContext) UnmarshalCodec(ctx context.Context, funcName string, value any) (any, error) {
	handler, ok := shardruntime.LookupCodecUnmarshal("github.com/99designs/gqlgen/codegen/testserver/splitpackages", funcName)
	if !ok {
		return nil, fmt.Errorf("unknown codec unmarshal function %s", funcName)
	}

	return handler(ctx, ec, value)
}

func (ec *executionContext) ParseFieldArgs(ctx context.Context, argsKey string, rawArgs map[string]any) (map[string]any, error) {
	return rawArgs, nil
}

func (ec *executionContext) InvokeResolver(ctx context.Context, objectName, fieldName string, obj any) (any, error) {
	handler, ok := shardruntime.LookupResolverInvoker("github.com/99designs/gqlgen/codegen/testserver/splitpackages", objectName, fieldName)
	if !ok {
		return nil, fmt.Errorf("unknown resolver invoker %s.%s", objectName, fieldName)
	}

	return handler(ctx, ec, obj)
}

func (ec *executionContext) LookupFieldContextHandler(objectName, fieldName string) (shardruntime.FieldContextHandler, bool) {
	return shardruntime.LookupFieldContext("github.com/99designs/gqlgen/codegen/testserver/splitpackages", objectName, fieldName)
}
func (ec *executionContext) _Query(ctx context.Context, sel ast.SelectionSet) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "Query")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "Query"))
	}
	return handler(ctx, ec, sel, nil)
}
func (ec *executionContext) ___Directive(ctx context.Context, sel ast.SelectionSet, obj *introspection.Directive) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__Directive")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__Directive"))
	}
	return handler(ctx, ec, sel, obj)
}
func (ec *executionContext) ___EnumValue(ctx context.Context, sel ast.SelectionSet, obj *introspection.EnumValue) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__EnumValue")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__EnumValue"))
	}
	return handler(ctx, ec, sel, obj)
}
func (ec *executionContext) ___Field(ctx context.Context, sel ast.SelectionSet, obj *introspection.Field) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__Field")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__Field"))
	}
	return handler(ctx, ec, sel, obj)
}
func (ec *executionContext) ___InputValue(ctx context.Context, sel ast.SelectionSet, obj *introspection.InputValue) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__InputValue")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__InputValue"))
	}
	return handler(ctx, ec, sel, obj)
}
func (ec *executionContext) ___Schema(ctx context.Context, sel ast.SelectionSet, obj *introspection.Schema) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__Schema")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__Schema"))
	}
	return handler(ctx, ec, sel, obj)
}
func (ec *executionContext) ___Type(ctx context.Context, sel ast.SelectionSet, obj *introspection.Type) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject("github.com/99designs/gqlgen/codegen/testserver/splitpackages", "__Type")
	if !ok {
		panic(fmt.Sprintf("missing object shard handler for %s", "__Type"))
	}
	return handler(ctx, ec, sel, obj)
}
func init() {
	scope := "github.com/99designs/gqlgen/codegen/testserver/splitpackages"
	_ = scope
	shardruntime.RegisterResolverInvoker(scope, "Query", "hello", func(ctx context.Context, oec shardruntime.ObjectExecutionContext, obj any) (any, error) {
		ec := oec.(*executionContext)
		fc := graphql.GetFieldContext(ctx)
		_ = fc
		return ec.resolvers.Query().Hello(ctx, fc.Args["name"].(string))
	})
	shardruntime.RegisterResolverInvoker(scope, "Query", "__type", func(ctx context.Context, oec shardruntime.ObjectExecutionContext, obj any) (any, error) {
		ec := oec.(*executionContext)
		fc := graphql.GetFieldContext(ctx)
		_ = fc
		return ec.IntrospectType(fc.Args["name"].(string))
	})
	shardruntime.RegisterResolverInvoker(scope, "Query", "__schema", func(ctx context.Context, oec shardruntime.ObjectExecutionContext, obj any) (any, error) {
		ec := oec.(*executionContext)
		return ec.IntrospectSchema()
	})
}

//go:embed "schema.graphql"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema.graphql", Input: sourceData("schema.graphql"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
