directive @goField(
	forceResolver: Boolean
	name: String
	omittable: Boolean
	type: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

enum Status {
	OK
	ERROR
}

scalar Time

input OuterInput {
	inner: InnerInput!
}

input OmittableInput {
	id: ID @goField(omittable: true)
	bool: Boolean @goField(omittable: true)
	str: String @goField(omittable: true)
	int: Int @goField(omittable: true)
	time: Time @goField(omittable: true)
	enum: Status @goField(omittable: true)
	scalar: ThirdParty @goField(omittable: true)
	object: OuterInput @goField(omittable: true)
}

extend type Query {
	inputOmittable(arg: OmittableInput!): String!
}
