// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package splitpackages

import (
	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/internal/gqlgenexec/shards/extras"
	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/internal/gqlgenexec/shards/extras_ee2d5c"
	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/internal/gqlgenexec/shards/prelude"
	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/internal/gqlgenexec/shards/schema"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
)

var schemaDescriptor = shardruntime.BuildSchema(
	extras.ShardDesc,
	extras_ee2d5c.ShardDesc,
	prelude.ShardDesc,
	schema.ShardDesc,
)
