// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package splitpackages

import (
	_ "github.com/99designs/gqlgen/codegen/testserver/splitpackages/internal/gqlgenexec/shards/directive_a8b6a1"
)
