// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package splitpackages

import (
	"context"

	"github.com/99designs/gqlgen/codegen/testserver/splitpackages/model"
)

type Stub struct {
	MutationResolver struct {
		Greet          func(ctx context.Context, name string) (string, error)
		PingFromExtras func(ctx context.Context) (string, error)
	}
	QueryResolver struct {
		Hello                            func(ctx context.Context, name string) (string, error)
		DirectiveArg                     func(ctx context.Context, arg string) (*string, error)
		DirectiveNullableArg             func(ctx context.Context, arg *int, arg2 *int, arg3 *string) (*string, error)
		DirectiveSingleNullableArg       func(ctx context.Context, arg1 *string) (*string, error)
		DirectiveInputNullable           func(ctx context.Context, arg *model.InputDirectives) (*string, error)
		DirectiveInput                   func(ctx context.Context, arg model.InputDirectives) (*string, error)
		DirectiveInputType               func(ctx context.Context, arg model.InnerInput) (*string, error)
		DirectiveInputOuter              func(ctx context.Context, arg model.OuterWrapperInput) (*string, error)
		DirectiveInputWithArgs           func(ctx context.Context, arg model.InputDirectivesWithArgs) (*string, error)
		DirectiveObject                  func(ctx context.Context) (*model.ObjectDirectives, error)
		DirectiveObjectWithCustomGoModel func(ctx context.Context) (*model.ObjectDirectivesWithCustomGoModel, error)
		DirectiveFieldDef                func(ctx context.Context, ret string) (string, error)
		DirectiveField                   func(ctx context.Context) (*string, error)
		DirectiveDouble                  func(ctx context.Context) (*string, error)
		DirectiveUnimplemented           func(ctx context.Context) (*string, error)
		GoodbyeFromExtras                func(ctx context.Context, name string) (string, error)
	}
	SubscriptionResolver struct {
		DirectiveArg           func(ctx context.Context, arg string) (<-chan *string, error)
		DirectiveNullableArg   func(ctx context.Context, arg *int, arg2 *int, arg3 *string) (<-chan *string, error)
		DirectiveDouble        func(ctx context.Context) (<-chan *string, error)
		DirectiveUnimplemented func(ctx context.Context) (<-chan *string, error)
	}
}

func (r *Stub) Mutation() MutationResolver {
	return &stubMutation{r}
}
func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}
func (r *Stub) Subscription() SubscriptionResolver {
	return &stubSubscription{r}
}

type stubMutation struct{ *Stub }

func (r *stubMutation) Greet(ctx context.Context, name string) (string, error) {
	return r.MutationResolver.Greet(ctx, name)
}
func (r *stubMutation) PingFromExtras(ctx context.Context) (string, error) {
	return r.MutationResolver.PingFromExtras(ctx)
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Hello(ctx context.Context, name string) (string, error) {
	return r.QueryResolver.Hello(ctx, name)
}
func (r *stubQuery) DirectiveArg(ctx context.Context, arg string) (*string, error) {
	return r.QueryResolver.DirectiveArg(ctx, arg)
}
func (r *stubQuery) DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (*string, error) {
	return r.QueryResolver.DirectiveNullableArg(ctx, arg, arg2, arg3)
}
func (r *stubQuery) DirectiveSingleNullableArg(ctx context.Context, arg1 *string) (*string, error) {
	return r.QueryResolver.DirectiveSingleNullableArg(ctx, arg1)
}
func (r *stubQuery) DirectiveInputNullable(ctx context.Context, arg *model.InputDirectives) (*string, error) {
	return r.QueryResolver.DirectiveInputNullable(ctx, arg)
}
func (r *stubQuery) DirectiveInput(ctx context.Context, arg model.InputDirectives) (*string, error) {
	return r.QueryResolver.DirectiveInput(ctx, arg)
}
func (r *stubQuery) DirectiveInputType(ctx context.Context, arg model.InnerInput) (*string, error) {
	return r.QueryResolver.DirectiveInputType(ctx, arg)
}
func (r *stubQuery) DirectiveInputOuter(ctx context.Context, arg model.OuterWrapperInput) (*string, error) {
	return r.QueryResolver.DirectiveInputOuter(ctx, arg)
}
func (r *stubQuery) DirectiveInputWithArgs(ctx context.Context, arg model.InputDirectivesWithArgs) (*string, error) {
	return r.QueryResolver.DirectiveInputWithArgs(ctx, arg)
}
func (r *stubQuery) DirectiveObject(ctx context.Context) (*model.ObjectDirectives, error) {
	return r.QueryResolver.DirectiveObject(ctx)
}
func (r *stubQuery) DirectiveObjectWithCustomGoModel(ctx context.Context) (*model.ObjectDirectivesWithCustomGoModel, error) {
	return r.QueryResolver.DirectiveObjectWithCustomGoModel(ctx)
}
func (r *stubQuery) DirectiveFieldDef(ctx context.Context, ret string) (string, error) {
	return r.QueryResolver.DirectiveFieldDef(ctx, ret)
}
func (r *stubQuery) DirectiveField(ctx context.Context) (*string, error) {
	return r.QueryResolver.DirectiveField(ctx)
}
func (r *stubQuery) DirectiveDouble(ctx context.Context) (*string, error) {
	return r.QueryResolver.DirectiveDouble(ctx)
}
func (r *stubQuery) DirectiveUnimplemented(ctx context.Context) (*string, error) {
	return r.QueryResolver.DirectiveUnimplemented(ctx)
}
func (r *stubQuery) GoodbyeFromExtras(ctx context.Context, name string) (string, error) {
	return r.QueryResolver.GoodbyeFromExtras(ctx, name)
}

type stubSubscription struct{ *Stub }

func (r *stubSubscription) DirectiveArg(ctx context.Context, arg string) (<-chan *string, error) {
	return r.SubscriptionResolver.DirectiveArg(ctx, arg)
}
func (r *stubSubscription) DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (<-chan *string, error) {
	return r.SubscriptionResolver.DirectiveNullableArg(ctx, arg, arg2, arg3)
}
func (r *stubSubscription) DirectiveDouble(ctx context.Context) (<-chan *string, error) {
	return r.SubscriptionResolver.DirectiveDouble(ctx)
}
func (r *stubSubscription) DirectiveUnimplemented(ctx context.Context) (<-chan *string, error) {
	return r.SubscriptionResolver.DirectiveUnimplemented(ctx)
}
