// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package prelude

import (
	"context"
	"fmt"
	"reflect"
	"strconv"
	"sync"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_Boolean = &shardruntime.ObjectChildLookup{
	TypeName: "Boolean",
	Kind:     ast.Scalar,
}
var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}
var type___Directive = &shardruntime.ObjectChildLookup{
	TypeName: "__Directive",
	Kind:     ast.Object,
	Children: []string{
		"name",
		"description",
		"isRepeatable",
		"locations",
		"args",
	},
}
var type___DirectiveLocation = &shardruntime.ObjectChildLookup{
	TypeName: "__DirectiveLocation",
	Kind:     ast.Enum,
}
var type___EnumValue = &shardruntime.ObjectChildLookup{
	TypeName: "__EnumValue",
	Kind:     ast.Object,
	Children: []string{
		"name",
		"description",
		"isDeprecated",
		"deprecationReason",
	},
}
var type___Field = &shardruntime.ObjectChildLookup{
	TypeName: "__Field",
	Kind:     ast.Object,
	Children: []string{
		"name",
		"description",
		"args",
		"type",
		"isDeprecated",
		"deprecationReason",
	},
}
var type___InputValue = &shardruntime.ObjectChildLookup{
	TypeName: "__InputValue",
	Kind:     ast.Object,
	Children: []string{
		"name",
		"description",
		"type",
		"defaultValue",
		"isDeprecated",
		"deprecationReason",
	},
}
var type___Type = &shardruntime.ObjectChildLookup{
	TypeName: "__Type",
	Kind:     ast.Object,
	Children: []string{
		"kind",
		"name",
		"description",
		"specifiedByURL",
		"fields",
		"interfaces",
		"possibleTypes",
		"enumValues",
		"inputFields",
		"ofType",
		"isOneOf",
	},
}
var type___TypeKind = &shardruntime.ObjectChildLookup{
	TypeName: "__TypeKind",
	Kind:     ast.Enum,
}

func init() {
	shardruntime.RegisterObject(splitScope, "__Directive", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___Directive(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "__EnumValue", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___EnumValue(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "__Field", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___Field(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "__InputValue", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___InputValue(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "__Schema", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___Schema(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "__Type", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return ___Type(ctx, ec, sel, obj)
	})
}

var __DirectiveImplementors = []string{"__Directive"}

func ___Directive(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __DirectiveImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__Directive")
		case "name":
			out.Values[i] = ec.ResolveField(ctx, "__Directive", "name", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__Directive", "description", field, obj)
		case "isRepeatable":
			out.Values[i] = ec.ResolveField(ctx, "__Directive", "isRepeatable", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "locations":
			out.Values[i] = ec.ResolveField(ctx, "__Directive", "locations", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "args":
			out.Values[i] = ec.ResolveField(ctx, "__Directive", "args", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var __EnumValueImplementors = []string{"__EnumValue"}

func ___EnumValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __EnumValueImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__EnumValue")
		case "name":
			out.Values[i] = ec.ResolveField(ctx, "__EnumValue", "name", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__EnumValue", "description", field, obj)
		case "isDeprecated":
			out.Values[i] = ec.ResolveField(ctx, "__EnumValue", "isDeprecated", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "deprecationReason":
			out.Values[i] = ec.ResolveField(ctx, "__EnumValue", "deprecationReason", field, obj)
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var __FieldImplementors = []string{"__Field"}

func ___Field(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __FieldImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__Field")
		case "name":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "name", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "description", field, obj)
		case "args":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "args", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "type":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "type", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "isDeprecated":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "isDeprecated", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "deprecationReason":
			out.Values[i] = ec.ResolveField(ctx, "__Field", "deprecationReason", field, obj)
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var __InputValueImplementors = []string{"__InputValue"}

func ___InputValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __InputValueImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__InputValue")
		case "name":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "name", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "description", field, obj)
		case "type":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "type", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "defaultValue":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "defaultValue", field, obj)
		case "isDeprecated":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "isDeprecated", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "deprecationReason":
			out.Values[i] = ec.ResolveField(ctx, "__InputValue", "deprecationReason", field, obj)
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var __SchemaImplementors = []string{"__Schema"}

func ___Schema(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __SchemaImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__Schema")
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "description", field, obj)
		case "types":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "types", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "queryType":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "queryType", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "mutationType":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "mutationType", field, obj)
		case "subscriptionType":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "subscriptionType", field, obj)
		case "directives":
			out.Values[i] = ec.ResolveField(ctx, "__Schema", "directives", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var __TypeImplementors = []string{"__Type"}

func ___Type(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, __TypeImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("__Type")
		case "kind":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "kind", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "name":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "name", field, obj)
		case "description":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "description", field, obj)
		case "specifiedByURL":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "specifiedByURL", field, obj)
		case "fields":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "fields", field, obj)
		case "interfaces":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "interfaces", field, obj)
		case "possibleTypes":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "possibleTypes", field, obj)
		case "enumValues":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "enumValues", field, obj)
		case "inputFields":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "inputFields", field, obj)
		case "ofType":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "ofType", field, obj)
		case "isOneOf":
			out.Values[i] = ec.ResolveField(ctx, "__Type", "isOneOf", field, obj)
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

func __resolveField___Directive(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.Directive).Name, nil
	case 1:
		return obj.(*introspection.Directive).Description(), nil
	case 2:
		return obj.(*introspection.Directive).IsRepeatable, nil
	case 3:
		return obj.(*introspection.Directive).Locations, nil
	case 4:
		return obj.(*introspection.Directive).Args, nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __Directive", fieldIdx)
	}
}

func __resolveField___EnumValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.EnumValue).Name, nil
	case 1:
		return obj.(*introspection.EnumValue).Description(), nil
	case 2:
		return obj.(*introspection.EnumValue).IsDeprecated(), nil
	case 3:
		return obj.(*introspection.EnumValue).DeprecationReason(), nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __EnumValue", fieldIdx)
	}
}

func __resolveField___Field(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.Field).Name, nil
	case 1:
		return obj.(*introspection.Field).Description(), nil
	case 2:
		return obj.(*introspection.Field).Args, nil
	case 3:
		return obj.(*introspection.Field).Type, nil
	case 4:
		return obj.(*introspection.Field).IsDeprecated(), nil
	case 5:
		return obj.(*introspection.Field).DeprecationReason(), nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __Field", fieldIdx)
	}
}

func __resolveField___InputValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.InputValue).Name, nil
	case 1:
		return obj.(*introspection.InputValue).Description(), nil
	case 2:
		return obj.(*introspection.InputValue).Type, nil
	case 3:
		return obj.(*introspection.InputValue).DefaultValue, nil
	case 4:
		return obj.(*introspection.InputValue).IsDeprecated(), nil
	case 5:
		return obj.(*introspection.InputValue).DeprecationReason(), nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __InputValue", fieldIdx)
	}
}

func __resolveField___Schema(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.Schema).Description(), nil
	case 1:
		return obj.(*introspection.Schema).Types(), nil
	case 2:
		return obj.(*introspection.Schema).QueryType(), nil
	case 3:
		return obj.(*introspection.Schema).MutationType(), nil
	case 4:
		return obj.(*introspection.Schema).SubscriptionType(), nil
	case 5:
		return obj.(*introspection.Schema).Directives(), nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __Schema", fieldIdx)
	}
}

func __resolveField___Type(ctx context.Context, ec shardruntime.ObjectExecutionContext, fieldIdx uint16, obj any) (any, error) {
	switch fieldIdx {
	case 0:
		return obj.(*introspection.Type).Kind(), nil
	case 1:
		return obj.(*introspection.Type).Name(), nil
	case 2:
		return obj.(*introspection.Type).Description(), nil
	case 3:
		return obj.(*introspection.Type).SpecifiedByURL(), nil
	case 4:
		fc := graphql.GetFieldContext(ctx)
		return obj.(*introspection.Type).Fields(fc.Args["includeDeprecated"].(bool)), nil
	case 5:
		return obj.(*introspection.Type).Interfaces(), nil
	case 6:
		return obj.(*introspection.Type).PossibleTypes(), nil
	case 7:
		fc := graphql.GetFieldContext(ctx)
		return obj.(*introspection.Type).EnumValues(fc.Args["includeDeprecated"].(bool)), nil
	case 8:
		return obj.(*introspection.Type).InputFields(), nil
	case 9:
		return obj.(*introspection.Type).OfType(), nil
	case 10:
		return obj.(*introspection.Type).IsOneOf(), nil
	default:
		return nil, fmt.Errorf("unknown field index %d for __Type", fieldIdx)
	}
}

// split_args_.gotpl — args for __Directive.args
func __splitArgs_field___Directive_args_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 *bool
	if tmp, ok := rawArgs["includeDeprecated"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("includeDeprecated"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalOBoolean2ᚖbool", tmp)
		if err != nil {
			return nil, err
		}
		if data != nil {
			arg0 = data.(*bool)
		}
	}
	args["includeDeprecated"] = arg0
	return args, nil
}

// split_args_.gotpl — args for __Field.args
func __splitArgs_field___Field_args_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 *bool
	if tmp, ok := rawArgs["includeDeprecated"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("includeDeprecated"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalOBoolean2ᚖbool", tmp)
		if err != nil {
			return nil, err
		}
		if data != nil {
			arg0 = data.(*bool)
		}
	}
	args["includeDeprecated"] = arg0
	return args, nil
}

// split_args_.gotpl — args for __Type.enumValues
func __splitArgs_field___Type_enumValues_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 bool
	if tmp, ok := rawArgs["includeDeprecated"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("includeDeprecated"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalOBoolean2bool", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(bool)
	}
	args["includeDeprecated"] = arg0
	return args, nil
}

// split_args_.gotpl — args for __Type.fields
func __splitArgs_field___Type_fields_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 bool
	if tmp, ok := rawArgs["includeDeprecated"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("includeDeprecated"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalOBoolean2bool", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(bool)
	}
	args["includeDeprecated"] = arg0
	return args, nil
}

// split_codecs_.gotpl — marshal
func marshalNBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(bool)
	res := graphql.MarshalBoolean(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__Directive")
	if !ok {
		panic("missing object shard handler for __Directive")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalN__DirectiveLocation2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(string)
	res := graphql.MarshalString(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalN__DirectiveLocation2ᚕstringᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__DirectiveLocation2string", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__EnumValue")
	if !ok {
		panic("missing object shard handler for __EnumValue")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__Field")
	if !ok {
		panic("missing object shard handler for __Field")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__InputValue")
	if !ok {
		panic("missing object shard handler for __InputValue")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	handler, ok := shardruntime.LookupObject(splitScope, "__Type")
	if !ok {
		panic("missing object shard handler for __Type")
	}
	{
		rv := reflect.ValueOf(value)
		if rv.Kind() == reflect.Struct {
			ptr := reflect.New(rv.Type())
			ptr.Elem().Set(rv)
			value = ptr.Interface()
		}
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	handler, ok := shardruntime.LookupObject(splitScope, "__Type")
	if !ok {
		panic("missing object shard handler for __Type")
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalN__TypeKind2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(string)
	res := graphql.MarshalString(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalOBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	_ = ctx
	v := value.(bool)
	res := graphql.MarshalBoolean(v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOBoolean2ᚖbool(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	_ = sel
	_ = ctx
	v := value.(*bool)
	res := graphql.MarshalBoolean(*v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOString2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	_ = ctx
	v := value.(string)
	res := graphql.MarshalString(v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalOString2ᚖstring(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	_ = sel
	_ = ctx
	v := value.(*string)
	res := graphql.MarshalString(*v)
	return res
}

// split_codecs_.gotpl — marshal
func marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — marshal
func marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	ret := make(graphql.Array, rv.Len())
	var wg sync.WaitGroup
	isLen1 := rv.Len() == 1
	if !isLen1 {
		wg.Add(rv.Len())
	}
	for i := 0; i < rv.Len(); i++ {
		i := i
		fc := &graphql.FieldContext{
			Index: &i,
		}
		ctx := graphql.WithFieldContext(ctx, fc)
		f := func(i int) {
			defer func() {
				if r := recover(); r != nil {
					ec.Error(ctx, ec.Recover(ctx, r))
					ret = nil
				}
			}()
			if !isLen1 {
				defer wg.Done()
			}
			ret[i] = ec.MarshalCodec(ctx, "marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType", sel, rv.Index(i).Interface())
		}
		if isLen1 {
			f(i)
		} else {
			go f(i)
		}
	}
	wg.Wait()
	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}
	return ret
}

// split_codecs_.gotpl — unmarshal
func unmarshalNBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalBoolean(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalN__DirectiveLocation2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalString(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalN__DirectiveLocation2ᚕstringᚄ(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	vSlice := graphql.CoerceList(value)
	if len(vSlice) == 0 {
		return ([]string)(nil), nil
	}
	res := make([]any, len(vSlice))
	for i := range vSlice {
		elemCtx := graphql.WithPathContext(ctx, graphql.NewPathWithIndex(i))
		elem, err := ec.UnmarshalCodec(elemCtx, "unmarshalN__DirectiveLocation2string", vSlice[i])
		if err != nil {
			return nil, err
		}
		res[i] = elem
	}
	for _, e := range res {
		if e != nil {
			sliceType := reflect.SliceOf(reflect.TypeOf(e))
			typedSlice := reflect.MakeSlice(sliceType, len(res), len(res))
			for i, elem := range res {
				if elem != nil {
					typedSlice.Index(i).Set(reflect.ValueOf(elem))
				}
			}
			return typedSlice.Interface(), nil
		}
	}
	return ([]string)(nil), nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalN__TypeKind2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalString(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOBoolean2bool(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalBoolean(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOBoolean2ᚖbool(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalBoolean(value)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}
	return &res, nil
}

// split_codecs_.gotpl — unmarshal
func unmarshalOString2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalString(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalOString2ᚖstring(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	res, err := graphql.UnmarshalString(value)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, err)
	}
	return &res, nil
}
