// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type InnerDirectives struct {
	Message string `json:"message"`
}

type InnerInput struct {
	ID int `json:"id"`
}

type InputDirectives struct {
	Text          string           `json:"text"`
	NullableText  *string          `json:"nullableText,omitempty"`
	Inner         *InnerDirectives `json:"inner"`
	InnerNullable *InnerDirectives `json:"innerNullable,omitempty"`
	ThirdParty    *ThirdParty      `json:"thirdParty,omitempty"`
}

type InputDirectivesWithArgs struct {
	Text string `json:"text"`
}

type ListFieldInput struct {
	Items []*string `json:"items,omitempty"`
}

type Mutation struct {
}

type ObjectDirectives struct {
	Text         string   `json:"text"`
	NullableText *string  `json:"nullableText,omitempty"`
	Order        []string `json:"order"`
}

type OmittableInput struct {
	ID     graphql.Omittable[*string]     `json:"id,omitempty"`
	Bool   graphql.Omittable[*bool]       `json:"bool,omitempty"`
	Str    graphql.Omittable[*string]     `json:"str,omitempty"`
	Int    graphql.Omittable[*int]        `json:"int,omitempty"`
	Time   graphql.Omittable[*time.Time]  `json:"time,omitempty"`
	Enum   graphql.Omittable[*Status]     `json:"enum,omitempty"`
	Scalar graphql.Omittable[*ThirdParty] `json:"scalar,omitempty"`
	Object graphql.Omittable[*OuterInput] `json:"object,omitempty"`
}

type OuterInput struct {
	Inner *InnerInput `json:"inner"`
}

type OuterWrapperInput struct {
	Inner *InputDirectives `json:"inner"`
}

type Query struct {
}

type Slices struct {
	Test1 []*string `json:"test1,omitempty"`
	Test2 []string  `json:"test2,omitempty"`
	Test3 []*string `json:"test3"`
	Test4 []string  `json:"test4"`
}

type Subscription struct {
}

type Status string

const (
	StatusOk    Status = "OK"
	StatusError Status = "ERROR"
)

var AllStatus = []Status{
	StatusOk,
	StatusError,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusOk, StatusError:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
