// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InnerDirectives struct {
	Message string `json:"message"`
}

type InnerInput struct {
	ID int `json:"id"`
}

type InputDirectives struct {
	Text          string           `json:"text"`
	NullableText  *string          `json:"nullableText,omitempty"`
	Inner         *InnerDirectives `json:"inner"`
	InnerNullable *InnerDirectives `json:"innerNullable,omitempty"`
	ThirdParty    *ThirdParty      `json:"thirdParty,omitempty"`
}

type InputDirectivesWithArgs struct {
	Text string `json:"text"`
}

type Mutation struct {
}

type ObjectDirectives struct {
	Text         string   `json:"text"`
	NullableText *string  `json:"nullableText,omitempty"`
	Order        []string `json:"order"`
}

type OuterWrapperInput struct {
	Inner *InputDirectives `json:"inner"`
}

type Query struct {
}

type Subscription struct {
}
